default: &default
  adapter: postgresql
  encoding: unicode
  username: earn
  password: earn
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe-App_development

test:
  <<: *default
  database: Recipe-App_test

production:
  <<: *default
  database: Recipe-App_production
